# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newcrawler.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 450)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.sourceTab = QtWidgets.QWidget()
        self.sourceTab.setObjectName("sourceTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sourceTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.sourceTab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.goButton = QtWidgets.QPushButton(self.sourceTab)
        self.goButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.goButton.setObjectName("goButton")
        self.horizontalLayout.addWidget(self.goButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sourceBrowser = QtWebKitWidgets.QWebView(self.sourceTab)
        self.sourceBrowser.setUrl(QtCore.QUrl("about:blank"))
        self.sourceBrowser.setObjectName("sourceBrowser")
        self.verticalLayout.addWidget(self.sourceBrowser)
        self.tabWidget.addTab(self.sourceTab, "")
        self.targetTab = QtWidgets.QWidget()
        self.targetTab.setObjectName("targetTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.targetTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.targetBrowser = QtWebKitWidgets.QWebView(self.targetTab)
        self.targetBrowser.setUrl(QtCore.QUrl("about:blank"))
        self.targetBrowser.setObjectName("targetBrowser")
        self.verticalLayout_2.addWidget(self.targetBrowser)
        self.tabWidget.addTab(self.targetTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.gridLayout = QtWidgets.QGridLayout(self.dataTab)
        self.gridLayout.setObjectName("gridLayout")
        self.dataTableWidget = QtWidgets.QTableWidget(self.dataTab)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.dataTableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.dataTab, "")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.widget)
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBox.setObjectName("toolBox")
        self.treePage = QtWidgets.QWidget()
        self.treePage.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.treePage.setObjectName("treePage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.treePage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.treePage)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.toolBox.addItem(self.treePage, "")
        self.rulesPage = QtWidgets.QWidget()
        self.rulesPage.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.rulesPage.setObjectName("rulesPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.rulesPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ruleTableWidget = QtWidgets.QTableWidget(self.rulesPage)
        self.ruleTableWidget.setColumnCount(3)
        self.ruleTableWidget.setObjectName("ruleTableWidget")
        self.ruleTableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.ruleTableWidget)
        self.toolBox.addItem(self.rulesPage, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 300, 100))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.rulesLineEdit = QtWidgets.QLineEdit(self.widget)
        self.rulesLineEdit.setObjectName("rulesLineEdit")
        self.verticalLayout_3.addWidget(self.rulesLineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.classComboBox = QtWidgets.QComboBox(self.widget)
        self.classComboBox.setObjectName("classComboBox")
        self.horizontalLayout_2.addWidget(self.classComboBox)
        self.addRemoveButton = QtWidgets.QPushButton(self.widget)
        self.addRemoveButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.addRemoveButton.setObjectName("addRemoveButton")
        self.horizontalLayout_2.addWidget(self.addRemoveButton)
        self.testButton = QtWidgets.QPushButton(self.widget)
        self.testButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.testButton.setObjectName("testButton")
        self.horizontalLayout_2.addWidget(self.testButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.buttonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.buttonsHorizontalLayout.setObjectName("buttonsHorizontalLayout")
        self.roleComboBox = QtWidgets.QComboBox(self.widget)
        self.roleComboBox.setObjectName("roleComboBox")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.buttonsHorizontalLayout.addWidget(self.roleComboBox)
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setObjectName("addButton")
        self.buttonsHorizontalLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(self.widget)
        self.removeButton.setObjectName("removeButton")
        self.buttonsHorizontalLayout.addWidget(self.removeButton)
        self.verticalLayout_3.addLayout(self.buttonsHorizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pageButton = QtWidgets.QPushButton(self.widget)
        self.pageButton.setObjectName("pageButton")
        self.horizontalLayout_3.addWidget(self.pageButton)
        self.pagerButton = QtWidgets.QPushButton(self.widget)
        self.pagerButton.setObjectName("pagerButton")
        self.horizontalLayout_3.addWidget(self.pagerButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.runButton = QtWidgets.QPushButton(self.widget)
        self.runButton.setObjectName("runButton")
        self.verticalLayout_3.addWidget(self.runButton)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.horizontalLayout_4.addWidget(self.splitter)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.goButton.setText(_translate("Dialog", "Go"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sourceTab), _translate("Dialog", "Source"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.targetTab), _translate("Dialog", "Target"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dataTab), _translate("Dialog", "Data"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.treePage), _translate("Dialog", "Tree"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.rulesPage), _translate("Dialog", "Rules"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Data Mining"))
        self.addRemoveButton.setText(_translate("Dialog", "Add"))
        self.testButton.setText(_translate("Dialog", "Test"))
        self.roleComboBox.setItemText(0, _translate("Dialog", "Titles Collector"))
        self.roleComboBox.setItemText(1, _translate("Dialog", "Page Changer"))
        self.roleComboBox.setItemText(2, _translate("Dialog", "Main Page"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.removeButton.setText(_translate("Dialog", "Remove"))
        self.pageButton.setText(_translate("Dialog", "Test Page"))
        self.pagerButton.setText(_translate("Dialog", "Test Pager"))
        self.runButton.setText(_translate("Dialog", "Run"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

