# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gtp.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.urlLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.urlLineEdit.setObjectName("urlLineEdit")
        self.horizontalLayout.addWidget(self.urlLineEdit)
        self.goButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goButton.sizePolicy().hasHeightForWidth())
        self.goButton.setSizePolicy(sizePolicy)
        self.goButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.goButton.setObjectName("goButton")
        self.horizontalLayout.addWidget(self.goButton)
        self.getButton = QtWidgets.QPushButton(self.layoutWidget)
        self.getButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.getButton.setObjectName("getButton")
        self.horizontalLayout.addWidget(self.getButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gtpWebView = QtWebKitWidgets.QWebView(self.layoutWidget)
        self.gtpWebView.setUrl(QtCore.QUrl("about:blank"))
        self.gtpWebView.setObjectName("gtpWebView")
        self.verticalLayout_2.addWidget(self.gtpWebView)
        self.verticalLayout_2.setStretch(1, 2)
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setMinimumSize(QtCore.QSize(250, 0))
        self.toolBox.setObjectName("toolBox")
        self.projectPage = QtWidgets.QWidget()
        self.projectPage.setGeometry(QtCore.QRect(0, 0, 250, 353))
        self.projectPage.setObjectName("projectPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.projectPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.projectPage)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.projectNameLineEdit = QtWidgets.QLineEdit(self.projectPage)
        self.projectNameLineEdit.setObjectName("projectNameLineEdit")
        self.horizontalLayout_8.addWidget(self.projectNameLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.newProjectButton = QtWidgets.QPushButton(self.projectPage)
        self.newProjectButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.newProjectButton.setObjectName("newProjectButton")
        self.horizontalLayout_7.addWidget(self.newProjectButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.openProjectButton = QtWidgets.QPushButton(self.projectPage)
        self.openProjectButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.openProjectButton.setObjectName("openProjectButton")
        self.horizontalLayout_7.addWidget(self.openProjectButton)
        self.saveProjectButton = QtWidgets.QPushButton(self.projectPage)
        self.saveProjectButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.saveProjectButton.setObjectName("saveProjectButton")
        self.horizontalLayout_7.addWidget(self.saveProjectButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.toolBox.addItem(self.projectPage, "")
        self.navigationPage = QtWidgets.QWidget()
        self.navigationPage.setGeometry(QtCore.QRect(0, 0, 250, 353))
        self.navigationPage.setObjectName("navigationPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.navigationPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.navigationPage)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.linksQueryLineEdit = QtWidgets.QLineEdit(self.navigationPage)
        self.linksQueryLineEdit.setObjectName("linksQueryLineEdit")
        self.gridLayout.addWidget(self.linksQueryLineEdit, 0, 1, 2, 1)
        self.linksButton = QtWidgets.QPushButton(self.navigationPage)
        self.linksButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.linksButton.setObjectName("linksButton")
        self.gridLayout.addWidget(self.linksButton, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.navigationPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 2, 1)
        self.nextQueryLineEdit = QtWidgets.QLineEdit(self.navigationPage)
        self.nextQueryLineEdit.setObjectName("nextQueryLineEdit")
        self.gridLayout.addWidget(self.nextQueryLineEdit, 2, 1, 1, 1)
        self.nextTextLineEdit = QtWidgets.QLineEdit(self.navigationPage)
        self.nextTextLineEdit.setObjectName("nextTextLineEdit")
        self.gridLayout.addWidget(self.nextTextLineEdit, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.navigationPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.testLinksButton = QtWidgets.QPushButton(self.navigationPage)
        self.testLinksButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.testLinksButton.setObjectName("testLinksButton")
        self.gridLayout.addWidget(self.testLinksButton, 2, 2, 1, 1)
        self.autoLinksButton = QtWidgets.QPushButton(self.navigationPage)
        self.autoLinksButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.autoLinksButton.setObjectName("autoLinksButton")
        self.gridLayout.addWidget(self.autoLinksButton, 3, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.navigationPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.baseURLineEdit = QtWidgets.QLineEdit(self.navigationPage)
        self.baseURLineEdit.setObjectName("baseURLineEdit")
        self.gridLayout_3.addWidget(self.baseURLineEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.navigationPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.delaySpinBox = QtWidgets.QDoubleSpinBox(self.navigationPage)
        self.delaySpinBox.setDecimals(1)
        self.delaySpinBox.setSingleStep(0.1)
        self.delaySpinBox.setProperty("value", 1.0)
        self.delaySpinBox.setObjectName("delaySpinBox")
        self.gridLayout_3.addWidget(self.delaySpinBox, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.linksTableWidget = QtWidgets.QTableWidget(self.navigationPage)
        self.linksTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.linksTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.linksTableWidget.setObjectName("linksTableWidget")
        self.linksTableWidget.setColumnCount(0)
        self.linksTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.linksTableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.removeLinksButton = QtWidgets.QPushButton(self.navigationPage)
        self.removeLinksButton.setObjectName("removeLinksButton")
        self.horizontalLayout_6.addWidget(self.removeLinksButton)
        self.clearLinksButton = QtWidgets.QPushButton(self.navigationPage)
        self.clearLinksButton.setObjectName("clearLinksButton")
        self.horizontalLayout_6.addWidget(self.clearLinksButton)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout.setStretch(2, 10)
        self.toolBox.addItem(self.navigationPage, "")
        self.dataCollectorPage = QtWidgets.QWidget()
        self.dataCollectorPage.setGeometry(QtCore.QRect(0, 0, 250, 353))
        self.dataCollectorPage.setObjectName("dataCollectorPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dataCollectorPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.dataCollectorPage)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.dataQueryLineEdit = QtWidgets.QLineEdit(self.dataCollectorPage)
        self.dataQueryLineEdit.setObjectName("dataQueryLineEdit")
        self.horizontalLayout_3.addWidget(self.dataQueryLineEdit)
        self.addDataQueryButton = QtWidgets.QPushButton(self.dataCollectorPage)
        self.addDataQueryButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.addDataQueryButton.setObjectName("addDataQueryButton")
        self.horizontalLayout_3.addWidget(self.addDataQueryButton)
        self.testDataQueryButton = QtWidgets.QPushButton(self.dataCollectorPage)
        self.testDataQueryButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.testDataQueryButton.setObjectName("testDataQueryButton")
        self.horizontalLayout_3.addWidget(self.testDataQueryButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.dataQueryListWidget = QtWidgets.QListWidget(self.dataCollectorPage)
        self.dataQueryListWidget.setDragEnabled(True)
        self.dataQueryListWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.dataQueryListWidget.setObjectName("dataQueryListWidget")
        self.verticalLayout_3.addWidget(self.dataQueryListWidget)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.removeDataQueryButton = QtWidgets.QPushButton(self.dataCollectorPage)
        self.removeDataQueryButton.setObjectName("removeDataQueryButton")
        self.horizontalLayout_4.addWidget(self.removeDataQueryButton)
        self.clearDataQueryButton = QtWidgets.QPushButton(self.dataCollectorPage)
        self.clearDataQueryButton.setObjectName("clearDataQueryButton")
        self.horizontalLayout_4.addWidget(self.clearDataQueryButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.toolBox.addItem(self.dataCollectorPage, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 266, 333))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dataTableWidget = QtWidgets.QTableWidget(self.page_3)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.dataTableWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.removeDataButton = QtWidgets.QPushButton(self.page_3)
        self.removeDataButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.removeDataButton.setObjectName("removeDataButton")
        self.horizontalLayout_5.addWidget(self.removeDataButton)
        self.clearDataButton = QtWidgets.QPushButton(self.page_3)
        self.clearDataButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.clearDataButton.setObjectName("clearDataButton")
        self.horizontalLayout_5.addWidget(self.clearDataButton)
        self.saveDataButton = QtWidgets.QPushButton(self.page_3)
        self.saveDataButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.saveDataButton.setObjectName("saveDataButton")
        self.horizontalLayout_5.addWidget(self.saveDataButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.toolBox.addItem(self.page_3, "")
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.goButton.setText(_translate("MainWindow", "GO"))
        self.getButton.setText(_translate("MainWindow", "GET"))
        self.label_6.setText(_translate("MainWindow", "Name"))
        self.newProjectButton.setText(_translate("MainWindow", "New"))
        self.openProjectButton.setText(_translate("MainWindow", "Open"))
        self.saveProjectButton.setText(_translate("MainWindow", "Save"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.projectPage), _translate("MainWindow", "Project"))
        self.label.setText(_translate("MainWindow", "Links CSS Query"))
        self.linksButton.setText(_translate("MainWindow", "LINKS"))
        self.label_2.setText(_translate("MainWindow", "Next CSS Query"))
        self.label_7.setText(_translate("MainWindow", "Next Text"))
        self.testLinksButton.setText(_translate("MainWindow", "Test"))
        self.autoLinksButton.setText(_translate("MainWindow", "Auto"))
        self.label_4.setText(_translate("MainWindow", "Base URL"))
        self.label_5.setText(_translate("MainWindow", "Delay"))
        self.removeLinksButton.setText(_translate("MainWindow", "Remove"))
        self.clearLinksButton.setText(_translate("MainWindow", "Clear"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.navigationPage), _translate("MainWindow", "Page Navigation"))
        self.label_3.setText(_translate("MainWindow", "CSS Query"))
        self.addDataQueryButton.setText(_translate("MainWindow", "Add"))
        self.testDataQueryButton.setText(_translate("MainWindow", "Test"))
        self.removeDataQueryButton.setText(_translate("MainWindow", "Remove"))
        self.clearDataQueryButton.setText(_translate("MainWindow", "Clear"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.dataCollectorPage), _translate("MainWindow", "Data Collection"))
        self.removeDataButton.setText(_translate("MainWindow", "Remove"))
        self.clearDataButton.setText(_translate("MainWindow", "Clear"))
        self.saveDataButton.setText(_translate("MainWindow", "Save"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Data"))

from PyQt5 import QtWebKitWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

